### ISSUE TITLE
Private endpoint returns unauthorized on 08-Calling-Api

### ISSUE THREAD

**Issue by justswim** [auth0-samples/auth0-react-sample#45]
Steps to repro:

Clone the rep
cd 08-Calling-Api
npm install
set .env file
npm start

I can log in and out and the UI works, but the private endpoint is always unauthorized. I'm getting this error in the console:

```
Error
    at middleware (/Users/ericlu/Sites/github/auth/08-Calling-Api/node_modules/express-jwt/lib/index.js:75:21)
    at Layer.handle [as handle_request] (/Users/ericlu/Sites/github/auth/08-Calling-Api/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/ericlu/Sites/github/auth/08-Calling-Api/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/ericlu/Sites/github/auth/08-Calling-Api/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/ericlu/Sites/github/auth/08-Calling-Api/node_modules/express/lib/router/layer.js:95:5)
    at /Users/ericlu/Sites/github/auth/08-Calling-Api/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/Users/ericlu/Sites/github/auth/08-Calling-Api/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/ericlu/Sites/github/auth/08-Calling-Api/node_modules/express/lib/router/index.js:271:10)
    at expressInit (/Users/ericlu/Sites/github/auth/08-Calling-Api/node_modules/express/lib/middleware/init.js:33:5)
    at Layer.handle [as handle_request] (/Users/ericlu/Sites/github/auth/08-Calling-Api/node_modules/express/lib/router/layer.js:95:5)

Error
    at /Users/ericlu/Sites/github/auth/08-Calling-Api/node_modules/express-jwt/lib/index.js:101:22
    at /Users/ericlu/Sites/github/auth/08-Calling-Api/node_modules/jsonwebtoken/index.js:54:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Any ideas on why the example is broken?
Thanks for your help!

**Comment by patrykcieszkowski** [comment]
Did you deal with the issue?

**Comment by tiagoalvesdulce** [comment]
any update?

**Comment by chenkie** [comment]
Closing this out as the samples have been deprecated in favor the [latest ones](https://github.com/auth0-samples/auth0-react-samples) :)

Check the 03-Calling-an-API sample there.
